version: '3'
networks:
  development:
  test:
volumes:
  db_data:
  gem_cache:
  shared_data:
services:
  groundhog_redis:
    image: redis:4.0-alpine
    command: redis-server
    networks:
      - development
      - test
    volumes:
      - shared_data:/var/shared/redis
    ports:
      - 9379:6379
  groundhog_db:
    image: mysql:8.0
    container_name: groundhog_db
    volumes:
      - db_data:/var/mysql/data
      - shared_data:/var/shared
    networks:
      - development
      - test
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 9336:3306
  groundhog_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: groundhog_app
    volumes:
      - .:/var/app
      - shared_data:/var/shared
      - gem_cache:/usr/local/bundle/gems
    networks:
      - development
    ports:
      - 9000:3000
    stdin_open: true
    tty: true
    env_file: .env.development
    entrypoint: dev-entrypoint.sh
    command: ['rails', 'server', '-p', '3000', '-b', '0.0.0.0']
    environment:
      RAILS_ENV: development
    depends_on:
      - groundhog_db
  groundhog_test:
    image: groundhog_groundhog_app
    container_name: groundhog_test
    volumes:
      - .:/var/app
      - shared_data:/var/shared
      - gem_cache:/usr/local/bundle/gems
    networks:
      - test
    ports:
      - 9001:3001
    stdin_open: true
    tty: true
    env_file: .env.test
    entrypoint: test-entrypoint.sh
    command: ["rails", "-v"]
    environment:
      RAILS_ENV: test
    depends_on:
      - groundhog_db