# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Docker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2

    - name: build
      run: docker-compose -f "docker-compose.yml" up -d --build
    
    - name: setup
      run:  docker-compose run --rm groundhog_app rails db:create && docker-compose run --rm groundhog_app rails db:migrate && docker-compose run --rm groundhog_app bundle install

    - name: rubocop
      run: docker-compose run --rm groundhog_app bundle exec rubocop
    
    - name: rspec
      run: docker-compose run --rm groundhog_app bundle exec rspec